CREATE TABLE IF NOT EXISTS ssbs( id INT NOT NULL AUTO_INCREMENT,
buyAt VARCHAR(20),
createdAt VARCHAR(22),
sellAt VARCHAR(22), stockName VARCHAR(122) NOT NULL, stopLoss VARCHAR(22),
targetPrice VARCHAR(22), type VARCHAR(10),PRIMARY KEY(id));